// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Location struct {
	ID               interface{}
	Name             string
	ParentLocationID interface{}
}

type Product struct {
	ID              interface{}
	Name            string
	ParentProductID interface{}
}

type Sample struct {
	ID             interface{}
	LocationID     interface{}
	ProductID      interface{}
	TimeRegistered time.Time
	LastUpdate     time.Time
	State          string
}

type SampleMod struct {
	ID          interface{}
	SampleID    interface{}
	Name        string
	TimeAdded   time.Time
	TimeRemoved sql.NullTime
}

type SampleNote struct {
	ID       interface{}
	SampleID interface{}
	Contents string
	TimeMade time.Time
}
