// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type AppliedTag struct {
	ID          interface{}
	SampleID    interface{}
	TagID       interface{}
	DateAdded   sql.NullTime
	DateRemoved sql.NullTime
}

type Location struct {
	ID               interface{}
	Name             string
	Description      sql.NullString
	ParentLocationID interface{}
}

type Product struct {
	ID              interface{}
	Name            string
	ParentProductID interface{}
	PartNumber      sql.NullString
}

type Sample struct {
	ID             interface{}
	LocationID     interface{}
	ProductID      interface{}
	TimeRegistered sql.NullTime
	LastUpdate     sql.NullTime
	State          string
	OwnerID        interface{}
	ProductIssue   sql.NullString
}

type SampleComment struct {
	ID        interface{}
	SampleID  interface{}
	Comment   string
	CreatedAt sql.NullTime
}

type SampleMod struct {
	ID          interface{}
	SampleID    interface{}
	Name        string
	TimeAdded   time.Time
	TimeRemoved sql.NullTime
}

type SampleNote struct {
	ID       interface{}
	SampleID interface{}
	Contents string
	TimeMade time.Time
}

type Tag struct {
	ID        interface{}
	Name      string
	Removable sql.NullBool
}

type User struct {
	ID   interface{}
	Name string
}
